# Generated by Django 5.2.7 on 2026-03-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_create_preferencias_padre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('pk_alumno', models.AutoField(db_column='pk_alumno', primary_key=True, serialize=False)),
                ('codigo_alumno', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=12)),
                ('grado', models.CharField(blank=True, max_length=10, null=True)),
                ('seccion', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlumnoMetrics',
            fields=[
                ('pk_alumno_metrics', models.AutoField(db_column='pk_alumno_metrics', primary_key=True, serialize=False)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('facial_area', models.JSONField(blank=True, null=True)),
                ('porcentaje_similitud', models.FloatField(blank=True, null=True)),
                ('ultima_captura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alumno_metrics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('pk_asistencia', models.AutoField(db_column='pk_asistencia', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('curso', models.CharField(blank=True, max_length=50, null=True)),
                ('aula', models.CharField(blank=True, max_length=10, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsistenciaDetalle',
            fields=[
                ('pk_asistencia_detalle', models.AutoField(db_column='pk_asistencia_detalle', primary_key=True, serialize=False)),
                ('porcentaje_similitud', models.FloatField(blank=True, null=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('estado_asistencia', models.CharField(blank=True, max_length=20, null=True)),
                ('imagen_capturada', models.CharField(blank=True, max_length=200, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'asistencia_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('pk_autorizacion', models.AutoField(db_column='pk_autorizacion', primary_key=True, serialize=False)),
                ('estado_autorizacion', models.CharField(blank=True, max_length=20, null=True)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'autorizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CodigoFamilia',
            fields=[
                ('pk_codigo_familia', models.AutoField(db_column='pk_codigo_familia', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'codigo_familia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('pk_comunicado', models.AutoField(db_column='pk_comunicado', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(blank=True, default='info', max_length=20, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_evento', models.DateField(blank=True, null=True)),
                ('dirigido_a', models.CharField(blank=True, max_length=50, null=True)),
                ('grado', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(blank=True, default='activo', max_length=20, null=True)),
                ('prioridad', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'comunicado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificacionPadre',
            fields=[
                ('pk_notificacion', models.AutoField(db_column='pk_notificacion', primary_key=True, serialize=False)),
                ('mensaje', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_envio', models.CharField(blank=True, max_length=20, null=True)),
                ('medio_envio', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'notificacion_padre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('pk_padre', models.AutoField(db_column='pk_padre', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'padre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalEducativo',
            fields=[
                ('pk_personal', models.AutoField(db_column='pk_personal', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('salon_asignado', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'personal_educativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreferenciasPadre',
            fields=[
                ('pk_preferencia', models.AutoField(db_column='pk_preferencia', primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('notificaciones_email', models.BooleanField(default=True)),
                ('notificaciones_sms', models.BooleanField(default=False)),
                ('notificar_asistencia', models.BooleanField(default=True)),
                ('notificar_calificaciones', models.BooleanField(default=True)),
                ('notificar_comportamiento', models.BooleanField(default=True)),
                ('frecuencia_resumen', models.CharField(default='semanal', max_length=20)),
            ],
            options={
                'db_table': 'preferencias_padre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('pk_rol', models.AutoField(db_column='pk_rol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
    ]
