import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 👇 *** IMPORTAR E INICIALIZAR TFJS Y BACKENDS SOLO UNA VEZ ***
import * as tf from "@tensorflow/tfjs";
import "@tensorflow/tfjs-backend-webgl";
import "@tensorflow/tfjs-backend-cpu";

// Inicializa el backend SOLO UNA VEZ cuando se carga el layout
tf.ready().then(() => {
  if (tf.getBackend() !== "webgl") {
    tf.setBackend("webgl");
  }
  // Opcional: log para depuración
  // console.log("TFJS backend inicializado:", tf.getBackend());
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}