"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# config/settings.py
from pathlib import Path
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
# Priorizamos el archivo local del proyecto sobre variables heredadas
# del terminal/IDE para evitar desajustes de conexión.
load_dotenv(BASE_DIR / '.env', override=True)


def env_bool(name, default=False):
    return os.getenv(name, str(default)).lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    raw_value = os.getenv(name, default)
    return [item.strip() for item in raw_value.split(',') if item.strip()]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-9_--!ysio(aiofs7mbq=-j92+9wf-eu$p4z@@qq^09sl78lxrx')
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Dependencias
    'rest_framework',
    'rest_framework_simplejwt',
    'channels',
    'corsheaders',

    # Apps del sistema
    'attendance',
    'users',
    'devices',
    'reports',
    'config_app',
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
ASGI_APPLICATION = 'config.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

WSGI_APPLICATION = 'config.wsgi.application'

USE_SQLITE = env_bool('USE_SQLITE', False)
DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite' if USE_SQLITE else 'postgresql').lower()
DB_CONN_MAX_AGE = int(os.getenv('DB_CONN_MAX_AGE', '60'))

if USE_SQLITE or DB_ENGINE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif DB_ENGINE in {'mysql', 'mariadb'}:
    import pymysql

    pymysql.install_as_MySQLdb()

    mysql_options = {
        'charset': os.getenv('DB_CHARSET', 'utf8mb4'),
        'init_command': f"SET sql_mode='{os.getenv('DB_SQL_MODE', 'STRICT_TRANS_TABLES')}'",
        'connect_timeout': int(os.getenv('DB_CONNECT_TIMEOUT', '10')),
    }

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'control_escolar'),
            'USER': os.getenv('DB_USER', 'root'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'CONN_MAX_AGE': DB_CONN_MAX_AGE,
            'OPTIONS': mysql_options,
        }
    }
elif DB_ENGINE in {'mssql', 'sqlserver', 'sql_server'}:
    mssql_options = {
        'driver': os.getenv('DB_DRIVER', 'ODBC Driver 18 for SQL Server'),
        'extra_params': os.getenv(
            'DB_EXTRA_PARAMS',
            'Encrypt=yes;TrustServerCertificate=yes',
        ),
        'connection_timeout': int(os.getenv('DB_CONNECT_TIMEOUT', '10')),
        'connection_retries': int(os.getenv('DB_CONNECTION_RETRIES', '3')),
        'connection_retry_backoff_time': int(os.getenv('DB_CONNECTION_RETRY_BACKOFF', '5')),
        'query_timeout': int(os.getenv('DB_QUERY_TIMEOUT', '0')),
    }

    DATABASES = {
        'default': {
            'ENGINE': 'mssql',
            'NAME': os.getenv('DB_NAME', 'control_escolar'),
            'USER': os.getenv('DB_USER', 'sa'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', r'localhost\SQLEXPRESS'),
            'PORT': os.getenv('DB_PORT', ''),
            'Trusted_Connection': os.getenv('DB_TRUSTED_CONNECTION', 'no'),
            'CONN_MAX_AGE': DB_CONN_MAX_AGE,
            'OPTIONS': mssql_options,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', os.getenv('PGDATABASE')),
            'USER': os.getenv('DB_USER', os.getenv('PGUSER')),
            'PASSWORD': os.getenv('DB_PASSWORD', os.getenv('PGPASSWORD')),
            'HOST': os.getenv('DB_HOST', os.getenv('PGHOST')),
            'PORT': os.getenv('DB_PORT', os.getenv('PGPORT', '5432')),
            'CONN_MAX_AGE': DB_CONN_MAX_AGE,
            'OPTIONS': {
                'sslmode': os.getenv('DB_SSLMODE', 'require'),
                'connect_timeout': 10,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Email notifications
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@feyalegria39.local')

# SMS notifications
SMS_BACKEND = os.getenv('SMS_BACKEND', 'console')
SMS_FROM_NUMBER = os.getenv('SMS_FROM_NUMBER', '')
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_FROM_NUMBER = os.getenv('TWILIO_FROM_NUMBER', '')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
